version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34.8-heroku
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_SECRET: ${PRISMA_SECRET}
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: prisma
            password: prisma
  postgres-db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
