version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.3.0
    working_directory: ~/elpisapi

    steps:
      - checkout

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test
