version: 2
jobs:
  pre:
    docker:
      - image: circleci/node:11.3.0
    working_directory: ~/elpisapi

    steps:
      - checkout
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash

  build:
    docker:
      - image: circleci/node:11.3.0
    working_directory: ~/elpisapi

    steps:
      - checkout

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test

workflows:
  version: 2
  pre_and_build:
    jobs:
      - pre
      - build
